[build]
command = "pnpm build:netlify"
publish = "."
edge_functions = ".netlify"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
